# https://github.com/DoranekoSystems/frida-ceserver/wiki/Config
[base]
# frida or memprocfs
engine = "frida"

[frida.general]
target =  ""
target_os = "ios"
# attach spawn enum
mode =  "attach"
binary_path = ""
# ia32 x64 arm arm64
arch = "arm64"
ceversion =  "7.5.2"
# Setting it to '0.0.0.0' allows connections from other PC
listen_host = "127.0.0.1"
listen_port = 52736

[frida.ipconfig]
frida_server_ip =  ""
# ceserver or memory-server
native_server = ""
native_server_ip =  ""
debugserver_ip =  ""
 
[frida.ssh_auto]
enable = false
ip = ""
username = ""
password = ""
ceserver_path =""
debugserver_path = ""

[frida.adb_auto]
enable = false
frida_server_path = ""
ceserver_path = ""
gdbserver_path = ""

[frida.extended_function]
custom_read_memory = false
fix_module_size =  false
manual_parser = false
java_info  = false
custom_symbol_loader =  ""
# mono:il2cpp_data_collector
data_collector = ""

[memprocfs.general]
# example:"pmem://C:\\pmem\\winpmem_x64.sys"
device = ""
# ia32 x64 arm arm64
arch = "x64"
ceversion =  "7.5.2"
# Setting it to '0.0.0.0' allows connections from other PC
listen_host = "127.0.0.1"
listen_port = 52736